env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/twonky-server
  tag: latest@sha256:108baa2de41a614500e9d496e1d9435a44a28fa98fb2b30b3c6827c8072ac768
persistence:
  config:
    enabled: true
    mountPath: /config
  data:
    enabled: true
    mountPath: /data
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 9000
        protocol: TCP
        targetPort: 9000

portal:
  enabled: true
