image:
  repository: tccr.io/truecharts/picoshare
  tag: 1.2.2@sha256:69e5ef1d1901bd23d2c3d8b42766a9c386af013d61074eaa0b1efb05862804e4
  pullPolicy: IfNotPresent

secretEnv:
  PS_SHARED_SECRET: "somesecretcode"
  LITESTREAM_BUCKET: ""
  LITESTREAM_ENDPOINT: ""
  LITESTREAM_ACCESS_KEY_ID: ""
  LITESTREAM_SECRET_ACCESS_KEY: ""

env:
  PORT: "{{ .Values.service.main.ports.main.port }}"

service:
  main:
    ports:
      main:
        port: 10209

persistence:
  data:
    enabled: true
    mountPath: "/data"

portal:
  enabled: true
