image:
  repository: tccr.io/truecharts/homepage
  tag: 0.6.4@sha256:7f8dca14a384fee816ebd564fbaccc8ff38723423a3928a88794b1299866b192
  pullPolicy: IfNotPresent

service:
  main:
    ports:
      main:
        port: 10352
        protocol: HTTP
        targetPort: 3000

persistence:
  config:
    enabled: true
    mountPath: /app/config

portal:
  enabled: true
