image:
  repository: tccr.io/truecharts/bookstack
  pullPolicy: IfNotPresent
  tag: 22.11.20221130@sha256:1f9e53ffb1f24664e57f2185ec73b6ec2f9f0fdba49bc8bd25a7bb1ceb22469b

env:
  DB_USER: "{{ .Values.mariadb.mariadbUsername }}"
  DB_DATABASE: "{{ .Values.mariadb.mariadbDatabase }}"
  APP_URL: ""
  DB_HOST:
    secretKeyRef:
      name: mariadbcreds
      key: plainhost
  DB_PASS:
    secretKeyRef:
      name: mariadbcreds
      key: mariadb-password
  APP_KEY:
    secretKeyRef:
      name: bookstack-secrets
      key: APP_KEY

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10112
        targetPort: 80

persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/config"

mariadb:
  enabled: true
  mariadbUsername: bookstack
  mariadbDatabase: bookstack
  existingSecret: "mariadbcreds"

portal:
  enabled: true
