image:
  repository: tccr.io/truecharts/neko-firefox
  pullPolicy: IfNotPresent
  tag: latest@sha256:050f201a417ff3e3b84afe9896551e15ebaf1444898efa16799d9464b84123b0

braveImage:
  repository: tccr.io/truecharts/neko-brave
  pullPolicy: IfNotPresent
  tag: latest@sha256:2c5772202021b757532825528d61b06c58779ac5c2e23176aa0ab8a0dba13de3

chromeImage:
  repository: tccr.io/truecharts/neko-chrome
  pullPolicy: IfNotPresent
  tag: latest@sha256:8f9218b37f877617ca8e567a7569799e316f0ceb2b8694d3f4cd4bd418fe8bc1

chromiumImage:
  repository: tccr.io/truecharts/neko-chromium
  pullPolicy: IfNotPresent
  tag: latest@sha256:88bf3b8e01a515e68f1a9e6ccc2e30bda8afccac877f134148baaf1743bb2589

edgeImage:
  repository: tccr.io/truecharts/neko-msedge
  pullPolicy: IfNotPresent
  tag: latest@sha256:f064c3d07698be8246af0d40146c45658907626d79b604a5283e8c4c43e83e70

remminaImage:
  repository: tccr.io/truecharts/neko-remmina
  pullPolicy: IfNotPresent
  tag: latest@sha256:20b95134d5a0147fcd0d388851fdfe244e9d5e8783b47ceb596aad64791d2f03

torImage:
  repository: tccr.io/truecharts/neko-tor
  pullPolicy: IfNotPresent
  tag: latest@sha256:6f5adfd2c149a7ff65ebe9894981bba20aa6cceb78ccc90459062605499009e4

vivaldiImage:
  repository: tccr.io/truecharts/neko-vivaldi
  pullPolicy: IfNotPresent
  tag: latest@sha256:703491e0563ecdbb16981649e24eec1e4af117d8f34d5bf44fb795901934625e

vlcImage:
  repository: tccr.io/truecharts/neko-vlc
  pullPolicy: IfNotPresent
  tag: latest@sha256:2bea841ee329b9f67aaaff7386705609afd7977aa18a96d0aff7b12d35177850

vncviewerImage:
  repository: tccr.io/truecharts/neko-vncviewer
  pullPolicy: IfNotPresent
  tag: latest@sha256:9d6680979372ae561fd157cc973d8e73a826ccf68773314169d2d761564c184d

xfceImage:
  repository: tccr.io/truecharts/neko-xfce
  pullPolicy: IfNotPresent
  tag: latest@sha256:debd52d2346d70ec062958967226b1c2cb33b7a70012b0dd528114abf555c0f1

imageSelector: "image"

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

secretEnv:
  NEKO_PASSWORD: userpass
  NEKO_PASSWORD_ADMIN: adminpass

env:
  NEKO_UDPMUX: 52100
  NEKO_TCPMUX: 52100
  # User Defined
  NEKO_SCREEN: 1920x1080@30
  NEKO_CONTROL_PROTECTION: false
  NEKO_IMPLICIT_CONTROL: false
  NEKO_LOCKS: ""
  NEKO_NAT1TO1: ""
  NEKO_IPFETCH: ""
  NEKO_PROXY: true

service:
  main:
    ports:
      main:
        port: 10294
        protocol: HTTP
        targetPort: 8080
  mux-udp:
    enabled: true
    ports:
      mux-udp:
        enabled: true
        port: 52100
        protocol: UDP
        targetPort: 52100
  mux-tcp:
    enabled: true
    ports:
      mux-tcp:
        enabled: true
        port: 52100
        protocol: TCP
        targetPort: 52100

portal:
  enabled: true
