image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/searx
  tag: latest@sha256:b00a39f3cf4ee0def8a6f2ed7688b8e17fbb0a9a276b2b86b62aaec7592554cd

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

env:
  BASE_URL: ""

service:
  main:
    ports:
      main:
        port: 8080
        protocol: TCP
        targetPort: 8080

persistence:
  config:
    enabled: true
    mountPath: /etc/searx

portal:
  enabled: true
