image:
  repository: tccr.io/truecharts/flexget
  pullPolicy: IfNotPresent
  tag: 3.5.21@sha256:788019acced1d459c75557fb9f2612930d7deccf6ea79fe4152fe03b024f9d0c

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10174
        targetPort: 5050

env:
  FG_LOG_LEVEL: info
  FG_LOG_FILE: flexget.log

secretEnv:
  FG_WEBUI_PASSWD: "jLeT78KBDPW"

persistence:
  config:
    enabled: true
    mountPath: "/config"

  data:
    enabled: true
    mountPath: "/data"

portal:
  enabled: true
