image:
  repository: tccr.io/truecharts/kitchenowl-web
  pullPolicy: IfNotPresent
  tag: latest@sha256:e46189b6e09a720ff56b5ccb8e7f5efe0b7a43cd72027b9c672bd0ad88da0d51

backendImage:
  repository: tccr.io/truecharts/kitchenowl-backend
  pullPolicy: IfNotPresent
  tag: latest@sha256:fc771f9cc6f6016e1d4d439dfbece48a8a26b78ff5ad8f179fde7a3483632335

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  FRONT_URL: "http://localhost:10246"
  # Backend listens on 5000 websockets.
  BACK_URL: "localhost:5000"

service:
  main:
    ports:
      main:
        protocol: HTTP
        targetPort: 80
        port: 10246

additionalContainers:
  backend:
    name: backend
    image: "{{ .Values.backendImage.repository }}:{{ .Values.backendImage.tag }}"
    env:
      - name: FRONT_URL
        value: "{{ .Values.env.FRONT_URL }}"
        # Backend also listens on 80, but afaik there is no use as of now
        # Changed port to 81 to avoid conflict with frontend
      - name: HTTP_PORT
        value: "81"
      - name: JWT_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: kitchenowl-secrets
            key: JWT_SECRET_KEY
    volumeMounts:
      - name: data
        mountPath: "/data"

persistence:
  data:
    enabled: true
    mountPath: "/data"

portal:
  enabled: true
