image:
  repository: tccr.io/truecharts/portainer-ce
  tag: 2.16.2@sha256:e838286b3a84886881e103bb3291b369135eb01ff27ba20351f7a932f4c1cbad
  pullPolicy: IfNotPresent

portainer:
  # Logo URL
  logo: ""
  # Enables Edge Compute Features
  edge_compute: false
  # Sets Snapshot interval
  snapshot_interval: 5m
  hide_labels:
    # - label1=value1
    # - label2=value2

serviceAccount:
  main:
    enabled: true

rbac:
  main:
    enabled: true
    rules:
      - apiGroups:
          - "*"
        resources:
          - "*"
        verbs:
          - "*"

probes:
  liveness:
    custom: true
    spec:
      httpGet:
        path: /
        port: 9443
        scheme: HTTPS
  readiness:
    custom: true
    spec:
      httpGet:
        path: /
        port: 9443
        scheme: HTTPS
  startup:
    custom: true
    spec:
      httpGet:
        path: /
        port: 9443
        scheme: HTTPS

service:
  main:
    ports:
      main:
        port: 10400
        protocol: HTTPS
        targetPort: 9443
  edge:
    enabled: true
    ports:
      edge:
        enabled: true
        port: 10401
        targetPort: 10401

persistence:
  data:
    enabled: true
    mountPath: "/data"
  cache:
    enabled: true
    mountPath: "/.cache"
    type: emptyDir

portal:
  enabled: true
