image:
  repository: tccr.io/truecharts/habridge
  pullPolicy: IfNotPresent
  tag: v5.4.1@sha256:62a13a2942c721e2590892b456f8b65456e649d5484c8ff5e8cadf190e10bbdb

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

secretEnv:
  SEC_KEY: ""

service:
  main:
    ports:
      main:
        targetPort: 8080
        port: 10146
  comm:
    enabled: true
    ports:
      comm:
        enabled: true
        targetPort: 50000
        port: 50000

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
