image:
  repository: tccr.io/truecharts/logitechmediaserver
  pullPolicy: IfNotPresent
  tag: 8.4.0@sha256:153632e648bffe9194efcb3fe166b288417834968cb83fb3c2ed4d140c3dedc1

env:
  HTTP_PORT: "{{ .Values.service.main.ports.main.port }}"

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 9000
  cli:
    enabled: true
    ports:
      cli:
        enabled: true
        port: 9090
        targetPort: 9090
  playertcp:
    enabled: true
    ports:
      slimprototcp:
        enabled: true
        port: 3483
        targetPort: 3483
  playerudp:
    enabled: true
    ports:
      slimprotoudp:
        enabled: true
        port: 3483
        protocol: UDP
        targetPort: 3483

persistence:
  config:
    enabled: true
    mountPath: /config

portal:
  enabled: true
