env:
  ALLOWED_TYPES: jpg,png,jpeg,bmp,gif
  ENABLE_AVIF: "false"
  QUALITY: "80"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/webp-server
  tag: latest@sha256:0b7a549cfaf63e2d098fd00cf0eef10ca536be748415ea07dcbeefd26106f694
persistence:
  storagecache:
    enabled: true
    mountPath: /opt/exhaust
  storagepics:
    enabled: true
    mountPath: /opt/pics
    readOnly: true
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 3333
        protocol: TCP
        targetPort: 3333

portal:
  enabled: true
