image:
  repository: tccr.io/truecharts/fluidd
  tag: 1.23.0@sha256:24b3604b02e6bd594d468f4cb373c6cee44400a05f962bc1c64a12894c7e2868
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10224
        targetPort: 80

portal:
  enabled: true
