image:
  repository: tccr.io/truecharts/immich-server
  tag: 1.42.0_65@sha256:c3ae0be2bf04432b5795e2de0ac36c88add774768890d61f3cdf2926b36fd8d6
  pullPolicy: IfNotPresent

mlImage:
  repository: tccr.io/truecharts/immich-ml
  tag: 1.42.0_65@sha256:d13d9c3406b95f216623c3877f43ec3a3c68a8d31144f30fc5da56f74ceed330
  pullPolicy: IfNotPresent

webImage:
  repository: tccr.io/truecharts/immich-web
  tag: 1.42.0_65@sha256:a0e915689d2a8b08a8690a565084d2564ef0d3251beaa945969820848ca281dd
  pullPolicy: IfNotPresent

proxyImage:
  repository: tccr.io/truecharts/immich-proxy
  tag: 1.42.0_65@sha256:1bd77ec11bda174d6b30f6fceb4ff57611297551322d0e1ad2c55d695a80fe75
  pullPolicy: IfNotPresent

command:
  - /bin/sh
  - ./start-server.sh

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

immich:
  enable_ml: true
  public_login_page_message: Immich
  disable_reverse_geocoding: false
  reverse_geocoding_precision: 3
  # simple | verbose
  log_level: simple
  mapbox_enable: false
  mapbox_key: ""

envFrom:
  - configMapRef:
      name: '{{ include "tc.common.names.fullname" . }}-server-config'
  - configMapRef:
      name: '{{ include "tc.common.names.fullname" . }}-common-config'
  - secretRef:
      name: '{{ include "tc.common.names.fullname" . }}-immich-secret'

probes:
  liveness:
    path: /server-info/ping
    type: HTTP
    port: 3001
  readiness:
    path: /server-info/ping
    type: HTTP
    port: 3001
  startup:
    path: /server-info/ping
    type: HTTP
    port: 3001

service:
  main:
    ports:
      main:
        port: 10323
        protocol: HTTP
        targetPort: 8080

persistence:
  uploads:
    enabled: true
    mountPath: /usr/src/app/upload

postgresql:
  enabled: true
  existingSecret: dbcreds
  postgresqlUsername: immich
  postgresqlDatabase: immich

redis:
  enabled: true
  existingSecret: rediscreds

portal:
  enabled: true
