image:
  repository: tccr.io/truecharts/memcached
  pullPolicy: IfNotPresent
  tag: 1.6.18@sha256:e53803598eedae2c5da839832bf49fcc054b3367608325ec15a2e51c299cca91

service:
  main:
    ports:
      main:
        port: 11211
        targetPort: 11211

portal:
  enabled: false

manifests:
  enabled: false
