image:
  repository: tccr.io/truecharts/jellyseerr
  tag: 1.4.0@sha256:0390ea422810294d21767361aaafa4ae32b0046871de515ba45ce74a2cbede04
  pullPolicy: IfNotPresent

env:
  PORT: "{{ .Values.service.main.ports.main.port }}"
  # User Defined
  JELLYFIN_TYPE: ""
  LOG_LEVEL: "info"

service:
  main:
    ports:
      main:
        port: 10241

persistence:
  config:
    enabled: true
    mountPath: "/app/config"

portal:
  enabled: true
