image:
  repository: tccr.io/truecharts/darktable
  pullPolicy: IfNotPresent
  tag: 3.8.1@sha256:4acc0162eeeb6b27575acbc1e2dbe466167cc33b40d65c9d7cc741e523b7be7b

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 3000
        port: 10129

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
