env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/wifi-card
  tag: latest@sha256:b4910db703e7bb776dd6609a810eb6abd3b5b323010f94e37165f319d2253622
persistence: {}
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

portal:
  enabled: false
