image:
  repository: tccr.io/truecharts/audiobookshelf
  tag: 2.2.12@sha256:0405d299aad5376d35f17204751b2d53a017f34c3a5337804d24d16dc8a65977
  pullPolicy: IfNotPresent

env:
  AUDIOBOOKSHELF_UID: "{{ .Values.security.PUID }}"
  AUDIOBOOKSHELF_GID: "{{ .Values.podSecurityContext.fsGroup }}"
  PORT: "{{ .Values.service.main.ports.main.port }}"
  TOKEN_SECRET:
    secretKeyRef:
      name: audiobookshelf-secrets
      key: TOKEN_SECRET

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

service:
  main:
    ports:
      main:
        port: 10223

probes:
  liveness:
    path: "/ping"
  readiness:
    path: "/ping"
  startup:
    path: "/ping"

persistence:
  config:
    enabled: true
    mountPath: "/config"
  audiobooks:
    enabled: true
    mountPath: "/audiobooks"
  metadata:
    enabled: true
    mountPath: "/metadata"

portal:
  enabled: true
