image:
  repository: tccr.io/truecharts/cloudflareddns
  pullPolicy: IfNotPresent
  tag: latest@sha256:363bfaf17566d4afb51fa52252811c4c16977cef8f92672a129e8e1ee27ea250

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

cloudflareddns:
  user: your.cf.email@example.com
  api_token: ""
  api_key: ""
  api_token_zone: ""
  interval: 300
  detect_mode: dig-whoami.cloudflare
  detect_override: ""
  log_level: 3
  host_zone_record:
    []
    # - domain: example.com
    #   zone: example.com
    #   record: A
    # - domain: foobar.com
    #   zone: foobar.com
    #   record: A
    # - domain: foobar.com
    #   zone: foobar.com
    #   record: AAAA

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

envFrom:
  - secretRef:
      name: '{{ include "tc.common.names.fullname" . }}-secret'

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

persistence:
  config:
    enabled: true
    mountPath: /config
  varrun:
    enabled: true

portal:
  enabled: false
