image:
  repository: tccr.io/truecharts/rsnapshot
  pullPolicy: IfNotPresent
  tag: 1.4.4@sha256:1af3550cc789e5301524b2df6bfdca28bf370cd477db80e02038899512acbbcb

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: false
