env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/songkong
  tag: latest@sha256:0dea325943374222a52955cfa9be6c1324c4c0316106a314083eba1ad2b01184
persistence:
  music:
    enabled: true
    mountPath: /music
  songkongconfig:
    enabled: true
    mountPath: /songkong
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 4567
        protocol: TCP
        targetPort: 4567

portal:
  enabled: true
