image:
  repository: tccr.io/truecharts/minio-console
  tag: 0.22.5@sha256:315bd6ab91eefcc4726e2addf748a72e9c0153151ed081eca27b35d017dedeaa
  pullPolicy: IfNotPresent

args: ["server"]

secretEnv:
  CONSOLE_PBKDF_PASSPHRASE: "changeme"
  CONSOLE_PBKDF_SALT: "changeme"

env:
  CONSOLE_MINIO_SERVER: ""

service:
  main:
    ports:
      main:
        port: 9090
        targetPort: 9090

securityContext:
  readOnlyRootFilesystem: false

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
