image:
  repository: tccr.io/truecharts/cups-server
  tag: latest@sha256:32a87edf84e8aca4abe51ae62452d0688f9475a8944d3e7ac5875f2fa9ca79cb
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

secretEnv:
  ADMIN_PASSWORD: "secretpass"

service:
  main:
    ports:
      main:
        port: 631
        targetPort: 631

persistence:
  config:
    enabled: true
    mountPath: "/etc/cups"
  dbus:
    enabled: true
    type: hostPath
    hostPath: "/var/run/dbus"
    mountPath: "/var/run/dbus"
    readOnly: false

portal:
  enabled: true
