image:
  repository: tccr.io/truecharts/calibre
  tag: 6.11.0@sha256:ad925a0149ce825013ce925e8f5a4fbed6fccefb6f45cb2044100ef32f98135b
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

secretEnv:
  PASSWORD: ""

env:
  CLI_ARGS:

service:
  main:
    ports:
      main:
        port: 8084
        targetPort: 8080
  webserver:
    enabled: true
    ports:
      webserver:
        enabled: true
        port: 8081
        targetPort: 8081

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
