image:
  repository: tccr.io/truecharts/openspeedtest
  pullPolicy: IfNotPresent
  tag: latest@sha256:16f364019f74acb65269c91e41ac9b00d14e4fc160fb86b3dcb18a47789b9dcf

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: HTTP
        targetPort: 3000
        port: 10256

portal:
  enabled: true
