image:
  repository: tccr.io/truecharts/wireshark
  pullPolicy: IfNotPresent
  tag: 3.6.5@sha256:e4387ede066be26c893fd37b1021f432e0eeb3cdc73f460a08b632fd1b5f4516

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  capabilities:
    add:
      - NET_ADMIN

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

hostNetwork: true

service:
  main:
    ports:
      main:
        targetPort: 3000
        protocol: HTTP
        port: 3000

probes:
  liveness:
    path: /
  readiness:
    path: /
  startup:
    path: /

persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: /config

portal:
  enabled: true
