env:
  BASIC_AUTH: "True"
  BASIC_AUTH_PASSWORD: x
  BASIC_AUTH_USERNAME: x
  DEBUG: "False"
  EXCLUDE_IPS: ""
  SKIP_ARCHIVED_LOGS: "False"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/goaccess-npm-logs
  tag: latest@sha256:a078fef3b0a1c199a7c7eab7f49a2d47b056cc8bd91e4bbe648a904ee38efbeb
persistence:
  hostpath1:
    enabled: true
    mountPath: /opt/log
    readOnly: true
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 7880
        protocol: TCP
        targetPort: 7880

portal:
  enabled: true
