image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/plextraktsync
  tag: latest@sha256:1c9b5a4c4e5f227e9d9807ac124cf44cbdd91a5f57d8f92225d51240eac3ec8b

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

tty: true
stdin: true

plexTraktSync:
  task: ""
  schedule: "0 */6 * * *"

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

persistence:
  config:
    enabled: true
    mountPath: /app/config

portal:
  enabled: false

cronjob:
  annotations: {}
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 2
