image:
  repository: tccr.io/truecharts/nextpvr
  tag: latest@sha256:ad85cc1edb266ade491bc710057cce3087103644e1660b8a335bac2af8db8214
  pullPolicy: IfNotPresent

env:
  HOST_IP: "localhost"

service:
  main:
    ports:
      main:
        port: 10183
        targetPort: 8866

persistence:
  config:
    enabled: true
    mountPath: "/config"
  recordings:
    enabled: true
    mountPath: "/recordings"
  buffer:
    enabled: true
    mountPath: "/buffer"

portal:
  enabled: true
