image:
  repository: tccr.io/truecharts/qdirstat
  tag: 23.01.1@sha256:a2a601ad87ed64b299f21413bfe035519db84cbf4de9bd8b8d4f14c9923ba3da
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10262
        targetPort: 5800
  vnc:
    enabled: true
    ports:
      vnc:
        enabled: true
        port: 10263
        targetPort: 5900

envFrom:
  - configMapRef:
      name: '{{ include "tc.common.names.fullname" . }}-qdirstat'

secretEnv:
  VNC_PASSWORD: ""

qdirstat:
  KEEP_APP_RUNNING: false
  DISPLAY_WIDTH: 1280
  DISPLAY_HEIGHT: 768
  SECURE_CONNECTION: false
  ENABLE_CJK_FONT: false

configmap:
  qdirstat:
    enabled: true
    data:
      ENABLE_CJK_FONT: '{{ ternary "1" "0" .Values.qdirstat.ENABLE_CJK_FONT }}'
      KEEP_APP_RUNNING: '{{ ternary "1" "0" .Values.qdirstat.KEEP_APP_RUNNING }}'
      SECURE_CONNECTION: '{{ ternary "1" "0" .Values.qdirstat.SECURE_CONNECTION }}'
      DISPLAY_WIDTH: "{{ .Values.qdirstat.DISPLAY_WIDTH }}"
      DISPLAY_HEIGHT: "{{ .Values.qdirstat.DISPLAY_HEIGHT }}"

persistence:
  config:
    enabled: true
    mountPath: "/config"
  storage:
    enabled: true
    mountPath: "/storage"

portal:
  enabled: true
