image:
  repository: tccr.io/truecharts/putty
  tag: 23.01.1@sha256:29d4e717dd0a78036018e5ff37fd0e693a4c8d6ab05647c117d6efad8c592976
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10266
        targetPort: 5800
  vnc:
    enabled: true
    ports:
      vnc:
        enabled: true
        port: 10267
        targetPort: 5900

envFrom:
  - configMapRef:
      name: '{{ include "tc.common.names.fullname" . }}-putty'

secretEnv:
  VNC_PASSWORD: ""

putty:
  KEEP_APP_RUNNING: false
  DISPLAY_WIDTH: 1280
  DISPLAY_HEIGHT: 768
  SECURE_CONNECTION: false
  DISABLE_RESTART_SESSION_DIALOG_WINDOW: false
  ENABLE_CJK_FONT: false

configmap:
  putty:
    enabled: true
    data:
      ENABLE_CJK_FONT: '{{ ternary "1" "0" .Values.putty.ENABLE_CJK_FONT }}'
      KEEP_APP_RUNNING: '{{ ternary "1" "0" .Values.putty.KEEP_APP_RUNNING }}'
      SECURE_CONNECTION: '{{ ternary "1" "0" .Values.putty.SECURE_CONNECTION }}'
      DISABLE_RESTART_SESSION_DIALOG_WINDOW: '{{ ternary "1" "0" .Values.putty.DISABLE_RESTART_SESSION_DIALOG_WINDOW }}'
      DISPLAY_WIDTH: "{{ .Values.putty.DISPLAY_WIDTH }}"
      DISPLAY_HEIGHT: "{{ .Values.putty.DISPLAY_HEIGHT }}"

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
