env:
  DATABASE_CONNECTION: ""
  HTTP_PASS: ""
  HTTP_USER: ""
  TUBESYNC_DEBUG: "False"
  TUBESYNC_HOSTS: ""
  TUBESYNC_WORKERS: "2"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/tubesync
  tag: latest@sha256:63da16dd74e2d9f8903619e475f23444c83ce66cff25bd30fc5ecdf3ccb12b61
persistence:
  config:
    enabled: true
    mountPath: /config
  downloads:
    enabled: true
    mountPath: /downloads
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 4848
        protocol: TCP
        targetPort: 4848

portal:
  enabled: true
