env:
  PORT: "3000"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/vertex
  tag: vstable@sha256:8b78afeb54a7bc0993dff1f25ae43ba765427dbc5913a16d69313eee96e6af0d
persistence:
  config:
    enabled: true
    mountPath: /vertex
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 3000
        protocol: TCP
        targetPort: 3000

portal:
  enabled: true
