image:
  repository: tccr.io/truecharts/ddns-go
  pullPolicy: IfNotPresent
  tag: 4.4.2@sha256:61987ca50e726929bcf3bdd9a0e6301a02d45a979651d310715c7af5cdc425f2

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 9876
        port: 10168

persistence:
  data:
    enabled: true
    mountPath: "/root"

portal:
  enabled: true
