image:
  repository: tccr.io/truecharts/actualserver
  pullPolicy: IfNotPresent
  tag: 23.1.12@sha256:511fd80baaba5cde7010a54ce7ea1842f110d09d6169b1cb37fc0b2ebf036f73

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

service:
  main:
    ports:
      main:
        port: 10293
        protocol: HTTP
        targetPort: 5006

persistence:
  server-files:
    enabled: true
    mountPath: "/app/server-files"
  user-files:
    enabled: true
    mountPath: "/app/user-files"

portal:
  enabled: true
