image:
  repository: tccr.io/truecharts/alist
  pullPolicy: IfNotPresent
  tag: 3.9.2@sha256:6db08c080580253262b5ce507d329065a23b5c04afd18d488957597fe32ae690

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 5244
        port: 10167

persistence:
  data:
    enabled: true
    mountPath: "/opt/alist/data"

portal:
  enabled: true
