image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/rust
  tag: latest@sha256:0b8d664e0bff16a8c67abe2623700f18d4958450deb50beaa94186c1ffac64db

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

secretEnv:
  USERNAME: ""
  PASSWRD: ""

env:
  GAME_ID: "258550"
  GAME_PARAMS: +server.maxplayers 10
  GAME_PORT: "28015"
  OXIDE_MOD: ""
  SERVER_DISCRIPTION: Simple Unraid Rust Docker Server
  SERVER_NAME: RustDockerServer
  VALIDATE: false

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

service:
  main:
    ports:
      main:
        port: 28015
        protocol: UDP
        targetPort: 28015

persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd

portal:
  enabled: true
