env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/acestream
  tag: latest@sha256:c42e6d58629b851944f464ec68901c12f4bf5dc66349b5c623c66b3e592c851d
persistence:
  acestreamcache:
    enabled: true
    mountPath: /srv/acestream/.ACEStream
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8008
        protocol: TCP
        targetPort: 6878

portal:
  enabled: true
