image:
  repository: tccr.io/truecharts/appsmith
  tag: 1.9.5@sha256:9d60b462c650987ea94c0068393f8eaea3a7f86cba3e2d9b7ae994ec8eed90f8
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  APPSMITH_ADMIN_EMAILS: "me@example.com,you@example.com"
  APPSMITH_REDIS_URL:
    secretKeyRef:
      name: rediscreds
      key: url

service:
  main:
    ports:
      main:
        port: 10217
        targetPort: 80
  supervisor:
    enabled: true
    ports:
      supervisor:
        enabled: true
        port: 10218
        targetPort: 9001

persistence:
  appsmithstacks:
    enabled: true
    mountPath: "/appsmith-stacks"

redis:
  enabled: true
  existingSecret: "rediscreds"
  redisUsername: appsmith
# mongodb:
#   enabled: true
#   mongodbUsername: appsmith
#   mongodbDatabase: appsmith
#   existingSecret: "mongodbcreds"

portal:
  enabled: true
