image:
  repository: tccr.io/truecharts/onlyoffice-ds
  tag: 7.2.2@sha256:b34811e1c197889b07da37d6f5f3d042393387634b858b24b0d9524ffd3c75ec
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

secretEnv:
  JWT_SECRET: "randomgeneratedstring"

env:
  WOPI_ENABLED: true
  JWT_ENABLED: true
  DB_TYPE: "postgres"
  DB_PORT: 5432
  DB_NAME: "{{ .Values.postgresql.postgresqlDatabase }}"
  DB_USER: "{{ .Values.postgresql.postgresqlUsername }}"
  REDIS_SERVER_PORT: 6379
  DB_HOST:
    secretKeyRef:
      name: dbcreds
      key: plainhost
  DB_PWD:
    secretKeyRef:
      name: dbcreds
      key: postgresql-password
  REDIS_SERVER_HOST:
    secretKeyRef:
      name: rediscreds
      key: plainhost
  REDIS_SERVER_PASS:
    secretKeyRef:
      name: rediscreds
      key: redis-password

probes:
  liveness:
    path: "/healthcheck"
  readiness:
    path: "/healthcheck"
  startup:
    path: "/healthcheck"

service:
  main:
    ports:
      main:
        port: 10043
        targetPort: 80

# Enabled postgres
postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: onlyoffice
  postgresqlDatabase: onlyoffice

# Enabled redis
redis:
  enabled: true
  existingSecret: "rediscreds"

portal:
  enabled: true
