env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/sourcegraph
  tag: 4.4.1@sha256:71f792ced9f26741373a56b7633acaa9321c4fff399cedb10fc824e6668aa8b7
persistence:
  applicationdatastoragepath:
    enabled: true
    mountPath: /var/opt/sourcegraph
  configstoragepath:
    enabled: true
    mountPath: /etc/sourcegraph
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  adminconsolepo:
    enabled: true
    ports:
      adminconsolepo:
        enabled: true
        port: 2633
        protocol: TCP
        targetPort: 2633
  grafanaport:
    enabled: true
    ports:
      grafanaport:
        enabled: true
        port: 3370
        protocol: TCP
        targetPort: 3370
  main:
    ports:
      main:
        port: 7080
        protocol: HTTP
        targetPort: 7080

portal:
  enabled: true
