env:
  SCPRIME_WALLET_PASSWORD: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/scprime
  tag: latest@sha256:65ada1acde6dcace6715db5f9a465b90265b0c8e12f62d85196c10fc770293cd
persistence:
  metadata:
    enabled: true
    mountPath: /scp-data
  storage:
    enabled: true
    mountPath: /storage
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  hostapiaddress:
    enabled: true
    ports:
      hostapiaddress:
        enabled: true
        port: 4283
        protocol: TCP
        targetPort: 4283
  main:
    ports:
      main:
        port: 4282
        protocol: TCP
        targetPort: 4282

portal:
  enabled: true
