image:
  repository: tccr.io/truecharts/briefkasten
  pullPolicy: IfNotPresent
  tag: latest@sha256:66eca1ef3b9ac562e8f7af7404d80396f034cf5b64d04e39f8ed96fe213e8541

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

briefkasten:
  general:
    nextauth_url: http://localhost:3000
  github:
    id: ""
    secret: ""
  google:
    id: ""
    secret: ""
  supabase:
    key:
    url:
    bucket_id:
  mail:
    from:
    server:

envFrom:
  - secretRef:
      name: '{{ include "tc.common.names.fullname" . }}-secret'
  - configMapRef:
      name: '{{ include "tc.common.names.fullname" . }}-config'

service:
  main:
    ports:
      main:
        port: 10349
        protocol: HTTP
        targetPort: 3000

probes:
  liveness:
    enabled: false
    type: HTTP
    path: /
  readiness:
    enabled: false
    type: HTTP
    path: /
  startup:
    enabled: false
    type: HTTP
    path: /

postgresql:
  enabled: true
  existingSecret: dbcreds
  postgresqlUsername: briefkasten
  postgresqlDatabase: briefkasten

portal:
  enabled: true
